### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by zhorabay** [zhorabay/Kanban-board#21]
GitHub repo link: https://github.com/zhorabay/Kanban-board/projects/1
We are 2 people in a team.
Student A - Assem Zhorabay
Student B - Bhushan Deshmukh

**Comment by V-Blaze** [comment]
## Hi @zhorabay, @bhushan354  

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Used correct Kanban board template✔
- All student C cards removed 👋 
- Correct Number of cards ✔

 ## Required Changes ♻️
- [ ] As stated in the project requirement, Each card should be assigned to the correct student. when a card is correctly assigned, the student's GitHub avatar should show beside the task. :+1: :+1: 

- - Your card:
![Screenshot from 2023-09-04 10-02-43](https://github.com/zhorabay/Kanban-board/assets/107632780/6cc95844-43e7-4032-b7ce-05fa599285a7)

- - Correctly assigned card:
![Screenshot from 2023-09-04 10-03-15](https://github.com/zhorabay/Kanban-board/assets/107632780/4af0a935-8cec-4cfd-8cb2-10ba7ca6d303)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @zhorabay and @bhushan354,

## Highlights
✔️ Assigned solo tasks

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
- [ ] Kindly assign the group tasks as you have assigned the solo tasks. You can assign multiple people to the same task.

  ![image](https://github.com/zhorabay/Kanban-board/assets/54848363/7f3b0455-8280-41bf-b7f4-e6393fcc0aa1)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skyv26** [comment]
## Hi @bhushan354 and @DammyShittu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDU0ZDgxYjUxOTBlYzI0MTViMDk5ZTNmYjQzYWNlNGZmNzU3NzQyNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Kanban Board Setup ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
